<a href="https://colab.research.google.com/github/diegomarlop/Actiivities_IH/blob/main/Activities_1_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Activities 1.08
##Activity 1

Do you think it is important to reduce the number of categories in a column if you can? How might it impact your model?

Discussion on reducing the number of categories in a column.

##Activity 2
Refer to the file files_for_activities/regression_data___.csv for this exercise.

1. Import the data from regression_data___.csv.
2. Select categorical columns.
3. Difference between One Hot Encoding, Label Encoding, and Ordinal Encoding.

In [12]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn import preprocessing
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv('regression_data___.csv')

In [4]:
data

AVGGIFT   HV1_log  IC1_transformed  IC5_transformed  gender  TARGET_D
0     15.500000  7.760467        17.343389         4.181353    Male      21.0
1      3.080000  6.208590        16.230984         4.150313    Male       3.0
2      7.500000  7.113956        18.047227         4.205057  Female      20.0
3      6.700000  5.783825        11.737110         4.055333    Male       5.0
4      8.785714  6.643790        12.494862         4.088969  Female      10.0
...         ...       ...              ...              ...     ...       ...
4665  15.500000  6.552508        15.280561         4.187901    Male      25.0
4666  11.857143  8.118803        15.029617         4.248632    Male      19.0
4667  11.333333  6.551080        15.742430         4.179506  Female      10.0
4668  13.000000  6.398595        13.326031         4.124159    Male      25.0
4669  17.923077  6.823286        17.417748         4.256304    Male      25.0

[4670 rows x 6 columns]

In [5]:
data['gender'].unique()

array(['Male', 'Female', 'U'], dtype=object)

In [6]:
y=data['TARGET_D']
X=data.drop('TARGET_D',axis=1)

In [7]:
X_num = X.select_dtypes(include=np.number)
X_cat = X.select_dtypes(include=np.object)

<ipython-input-7-27b02f0cea58>:2: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_cat = X.select_dtypes(include=np.object)


In [ ]:
X_cat

In [9]:
#suponiendo que el mejor proceso para lo numérico es normalizar o estamos probando con diferentes transformaciones 
from sklearn.preprocessing import Normalizer
transformer =Normalizer().fit(X_num)
x_norm=transformer.transform(X_num)

In [10]:
#Este es el metodo de OneHote
encoder=OneHotEncoder(drop='first').fit(X_cat)
encoder=encoder.transform(X_cat).toarray()
encoder

array([[1., 0.],
       [1., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [1., 0.],
       [1., 0.]])

In [13]:
#Este de labelEncoder
from sklearn import preprocessing
labels = preprocessing.LabelEncoder().fit(X_cat).transform(X_cat)
labels

array([1, 1, 0, ..., 0, 1, 1])

In [14]:
#Este el de OrdinalEncoder
labels2 = preprocessing.OrdinalEncoder().fit(X_cat).transform(X_cat)
labels2

array([[1.],
       [1.],
       [0.],
       ...,
       [0.],
       [1.],
       [1.]])

## Activity 3
Check the difference between MSE and RMSE. Which one is bigger? Does it matter?

There is another measure of accuracy called "adjusted R-square". How is this different from R-square?

Read this [article](https://blog.minitab.com/en/adventures-in-statistics-2/multiple-regession-analysis-use-adjusted-r-squared-and-predicted-r-squared-to-include-the-correct-number-of-variables) and let's discuss it in class.

In [15]:
#ahora vamos a concatenar nuestra info primitivamente numérica, junto con la nueva numérica que viene de las categorías

#Vamos a elegir la OneHot
X=np.concatenate((x_norm,encoder),axis=1)

In [16]:
X

array([[0.62312259, 0.31198208, 0.69722951, 0.16809648, 1.        ,
        0.        ],
       [0.16988261, 0.34244528, 0.89524739, 0.22891755, 1.        ,
        0.        ],
       [0.35345786, 0.3352645 , 0.85052457, 0.19817472, 0.        ,
        0.        ],
       ...,
       [0.54236194, 0.313505  , 0.75336132, 0.20001218, 0.        ,
        0.        ],
       [0.6463473 , 0.31813189, 0.66255726, 0.20504914, 1.        ,
        0.        ],
       [0.68267219, 0.25989219, 0.66342472, 0.16211839, 1.        ,
        0.        ]])

In [17]:
#lo que vamos a hacer ahora, es separa el arreglo X en un % para entrenar un modelo y otro % para ponerlo a prueba
#recordando que y=data['TARGET_D]
from sklearn.model_selection import train_test_split
#un rango aceptable para probar un modelo es que el test_size sea entre 30% al 10%, lo más nomral es 20% al 25%

#podemos tener un control de la selección aleatoria para que siempre sea la misma selección aleatoria
#no importa cuantas veces corramos esta celda con random state
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=5)

#El sampleo lo hace de manera aleatoria

In [18]:
len(X_train)# Aqui podemos ver que la longitud de X_train es del 80% del total de los datos 

3736

In [19]:
len(X_num)#Aqui tenemos el total

4670

In [20]:
len(X_test)#Aqui tenemos el restante 20%

934

In [21]:
#por fin haciendo el modelo lineal, con unna regresión
from sklearn import linear_model
lm=linear_model.LinearRegression()

#Aquí ya ajustamos la maquinaria rpevia
model=lm.fit(X_train,y_train)

In [22]:
predictions=lm.predict(X_test)

In [23]:
predictions[:10]

array([ 7.36806692,  6.31060605, 16.52810908, 15.36381862, 18.16153652,
       10.66650874, 10.63267327,  6.14040698,  7.24972453, 19.88459948])

In [24]:
y_test[:10]

2932     5.0
3535     4.0
2834    10.0
2960     5.0
4612    21.0
4483     3.0
417     10.0
975      4.0
2059     5.0
4350    10.0
Name: TARGET_D, dtype: float64

In [26]:
#Aquí calculamos el r^2 que nos dice qué tanto se aproximan los datos reales a la recta calculada
from sklearn.metrics import mean_squared_error, r2_score
r2_score(y_test,predictions)

0.47761993995399155

In [28]:
mse=mean_squared_error(y_test,predictions)
print(mse)

52.77716601601956


In [31]:
#RMSE
import math
rmse=math.sqrt(mse)
rmse

7.264789468113963